export const KOL_CATEGORIES = [
    "Family",
    "Lifestyle",
    "Healthy",
    "Fashion",
    "Muslim Fashion",
    "Hijabi",
    "Travelling",
    "Automotive",
    "Home Living",
    "Cooking",
    "Comedian",
    "Beauty",
    "Korean Beauty",
    "Couple",
    "Education",
    "Office Life",
    "Moms and Kids",
    "Foodies",
    "DIY",
    "Sporty",
    "Musisi",
    "Cinema",
    "Storyteller",
    "Gamers",
    "Gadget",
    "Mahasiswa",
    "Gen Z",
    "Community",
    "Local Explorer",
    "Dancer",
    "Cosplayer",
    "Streamer",
    "Kpopers"
] as const;

export type KolCategory = typeof KOL_CATEGORIES[number];
