export const KOL_CATEGORIES = [
    "Automotive",
    "Beauty",
    "Cinema",
    "Comedian",
    "Community",
    "Cooking",
    "Cosplayer",
    "Couple",
    "Dancer",
    "DIY",
    "Education",
    "Family",
    "Fashion",
    "Foodies",
    "Gadget",
    "Gamers",
    "Gen Z",
    "Healthy",
    "Hijabi",
    "Home Living",
    "Korean Beauty",
    "Kpopers",
    "Lifestyle",
    "Local Explorer",
    "Mahasiswa",
    "Moms and Kids",
    "Musisi",
    "Muslim Fashion",
    "Office Life",
    "Sporty",
    "Storyteller",
    "Streamer",
    "Travelling"
] as const;

export type KolCategory = typeof KOL_CATEGORIES[number];
